import type { Metadata } from 'next'
import RestaurantNavBar from '../components/RestaurantNavBar'
import Menu from '../components/Menu'
import prisma from '@/database'
import { Item } from '@prisma/client'

export const metadata: Metadata = {
  title: 'Menu of Milestones Grill (Toronto) | OpenTables',
  description: 'Generated by create next app',
}

const fetchRestaurantMenu = async (slug: string): Promise<Item[]> => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      items: true,
    },
  })

  if (!restaurant) throw new Error()

  return restaurant.items
}

const RestaurantMenuPage = async ({ params }: { params: { slug: string } }) => {
  const items = await fetchRestaurantMenu(params.slug)

  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestaurantNavBar slug={params.slug} />
        <Menu items={items} />
      </div>
    </>
  )
}

export default RestaurantMenuPage
