import type { Metadata } from 'next'
import Header from './components/Header'
import Form from './components/Form'
import prisma from '@/database'
import { notFound } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Reserve at Milestones Grill (Toronto) | OpenTables',
  description: 'Generated by create next app',
}

const fetchRestaurantBySlug = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
  })

  if (!restaurant) notFound()

  return restaurant
}

const ReservationPage = async ({
  params,
  searchParams,
}: {
  params: { slug: string }
  searchParams: {
    date: string
    partySize: string
  }
}) => {
  const restaurant = await fetchRestaurantBySlug(params.slug)

  return (
    <>
      <div className="border-t h-screen">
        <div className="py-9 w-4/5 m-auto">
          <Header
            image={restaurant.main_image}
            name={restaurant.name}
            date={searchParams.date}
            partySize={searchParams.partySize}
          />
          <Form
            slug={restaurant.slug}
            partySize={searchParams.partySize}
            date={searchParams.date}
          />
        </div>
      </div>
    </>
  )
}

export default ReservationPage
