import type { Metadata } from 'next'
import { RestaurantCard, Header } from '@/app/components'
import prisma from '@/database'
import { Cuisine, Location, PRICE, Review } from '@prisma/client'

export const metadata: Metadata = {
  title: 'OpenTables',
  description: 'Generated by create next app',
}

export interface RestaurantCardType {
  id: string
  name: string
  slug: string
  main_image: string
  price: PRICE
  cuisines: Cuisine
  locations: Location
  reviews: Review[]
}

const fetchRestaurants = async (): Promise<RestaurantCardType[]> => {
  const restaurants = await prisma.restaurant.findMany({
    select: {
      id: true,
      name: true,
      main_image: true,
      price: true,
      cuisines: true,
      locations: true,
      slug: true,
      reviews: true,
    },
  })

  return restaurants
}

export default async function Home() {
  const restaurants = await fetchRestaurants()

  return (
    <main>
      <Header />
      <div className="py-3 px-3 mt-5 flex flex-wrap justify-center">
        {restaurants.length > 0 &&
          restaurants.map((restaurant) => (
            <RestaurantCard key={restaurant.id} restaurant={restaurant} />
          ))}
      </div>
    </main>
  )
}
